### ISSUE TITLE
Good Good Study Day Day Up - 2020-12-05

### ISSUE THREAD

**Issue by FORMAT-qi** [t86/good-good-study-day-day-up#13]
1. [html]HTML5拖拽事件的顺序是什么？
2. [css]怎样在@keyframes中使用CSS变量
3. [js]请解释下为什么下面第一种方式会报错而第二种不会？
4. [软技能]你自己做过哪些完整项目，说说看

**Comment by FORMAT-qi** [comment]
1. [html]HTML5拖拽事件的顺序是什么？

传统方式
- PC：mousedonw``mousemove``mouseup
- 移动端：touchstart``touchmove``touchend
- 原理：通过计算坐标的方式来实现元素的可视化移动。

HTML5原生拖拽
- dragstart``drag``dragenter``dragover``dragleave``drop``dragend
- 原理：通过对被拖动元素和拖动目标元素进行事件监听，实现拖动效果

*区别
- 传统方式是实现元素的实时移动，HTML5原生拖拽事件是体现元素的拖拽结果，需要确定拖拽的目标区域，如应用于拖拽上传。

2.怎样在@Keyframes中使用CSS变量
SS变量可以和CSS动画一起使用，不论是在一般的HTML元素还是内联SVG元素上。只需要记住在想添加动画的元素的选择器上定义自定义属性，然后使用var()函数在@keyframes中引用。
    比如，给SVG的一个有类.bubble的<ellipse>元素添加动画，CSS代码如下：
```css
.bubble {
  --direction-y: 30px;
  --transparency: 0;
  animation: bubbling 3s forwards infinite;
}

@keyframes bubbling {
  0% {
    transform: translatey(var(--direction-y));
    opacity: var(--transparency);
  }
  40% {
    opacity: calc(var(--transparency) + 0.2);
  }
  70% {
    opacity: calc(var(--transparency) + 0.1);
  }
  100% {
    opacity: var(--transparency);
  }
}
```
3. [js]请解释下为什么下面第一种方式会报错而第二种不会？
object的键会被自动转为字符串。
但是obj.name 属性名只能是字符串，不能是数字, 因为会被当成小数点。
第一种可以使用object[8] = 8;
第二种会被转成字符串所以不会报错。
